### ISSUE TITLE
[Bug]: config files not deployed via pip install

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/dvas#302]
### Is there already an issue for this?

- [X] I found no existing issue for this bug.

### Describe the bug

v1.2.0 of the code was deployed in the wake of #298, with a correction of some of the paths inside ``MANIFEST.in``. However, the pip installation still fails. All the necessary files are correctly present in the tarball, such that doing a ``pip install -e . `` (and the tarball downloaded from PyPI) works. However, doing a regular ``pip install''. fails to copy the config_files over.

@msommer24: fyi - I'll need to fix these before the installation works as intended. 

### Environment

```markdown
- OS: any
- Python: 3.11
- dvas: 1.2.0
```

### Code of Conduct

- [X] I agree to follow the dvas Code of Conduct.

**Comment by fpavogt** [comment]
Will be fixed with #303. The problem is that the config files were not located within a package, such that they would be shipped to PyPI via ``MANIFEST.in'', but would then not be installed via ``pip install''. Moving the config folder in a different location fixes the problem.

**Comment by fpavogt** [comment]
@msommer24: fixes were implemented in v1.2.1, which is now available on PyPI. It should all work now ... fingers crossed !

**Comment by msommer24** [comment]
@fpavogt: That sounds very good. I will install and test new version next week. Thanks again.

**Comment by fpavogt** [comment]
@msommer24: noted. When you do, please note that dvas now only tolerates python 3.10 or 3.11 (just in case you had an environment setup with 3.12+ previously).

**Comment by msommer24** [comment]
Today, I had time to install and test new dvas version. I installed a python 3.11 for this. I followed the instructions and all seems fine. The full processing is started... (and will need some time.) 

Only very small thing I found is a wrong command (which I copied and got an error) in the doc at [https://meteoswiss.github.io/dvas/running_recipes.html#execution-of-a-dvas-recipe](https://meteoswiss.github.io/dvas/running_recipes.html#execution-of-a-dvas-recipe). There is a `uaii22.rcp` instead of `uaii2022.rcp`.
